# Generated by Django 3.2.12 on 2022-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Value Plans', 'Value Plans'), ('Popular Plans', 'Popular Plans'), ('Annual Plans', 'Annual Plans')], max_length=100, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('validity_in_days', models.PositiveIntegerField(null=True)),
                ('voice', models.CharField(max_length=100, null=True)),
                ('data_per_day', models.PositiveIntegerField(null=True)),
                ('sms_per_day', models.PositiveIntegerField(null=True)),
                ('add_ons', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plan',
                'db_table': 'Plan',
            },
        ),
    ]
